"""Pydantic v2 domain models (port of ``src/types.ts``).

Split by domain to keep files readable. Cross-domain references are done via
string literal types (see ``enums``) and simple field types (``str`` for IDs,
``list[float]`` for embeddings, ``datetime`` for timestamps).
"""

from app.schemas.alert import (
    AlertRule,
    AlertRulePreview,
    ConditionType,
    ParsedCondition,
    PatronAlert,
    TableRoundSnapshot,
)
from app.schemas.analysis import (
    NextActionRecommendation,
    PatronAnalysisReport,
    ReportStatus,
)
from app.schemas.chat import ChatMessage, ChatRole, ChatSession
from app.schemas.enums import (
    ActivityType,
    AdminDecision,
    AgentNodeStatus,
    CreditBand,
    EscalationTier,
    InteractionType,
    OccupancyTrend,
    OfferApprovalDecision,
    OfferCreatedBy,
    OfferStatus,
    OfferType,
    PatronRegion,
    PatronTier,
    RecommendationStatus,
    RiskCaseStatus,
    RiskLevel,
    SourceOfFundsRisk,
    TableGameType,
    TableStatus,
)
from app.schemas.offer import (
    CampaignRun,
    OfferApprovalAudit,
    OfferApprovalReview,
    OfferCatalog,
    OfferRecommendation,
)
from app.schemas.patron import (
    PatronActivityEvent,
    PatronInteractionRecord,
    PatronInteractionDetail,
    PatronProfile,
)
from app.schemas.pr import PRAgentProfile, PRAssignment, PrKpiResult, PrMetrics, KpiSearchResult
from app.schemas.risk import (
    AdminReviewRecord,
    AgentNodeState,
    FinancialAssessment,
    FinancialChecklistItem,
    LossChasingAssessment,
    PatronRiskCase,
    RiskCaseTimelineEvent,
)
from app.schemas.table import (
    MinBetAudit,
    MinBetCandidate,
    MinBetChangeSource,
    MinBetRecommendation,
    MinBetRecommendationDrivers,
    MinBetRecommendationStatus,
    PatronTableSession,
    TableStateHistory,
    TableStateSnapshot,
)

__all__ = [
    "ActivityType",
    "AdminDecision",
    "AdminReviewRecord",
    "AgentNodeState",
    "AgentNodeStatus",
    "AlertRule",
    "AlertRulePreview",
    "CampaignRun",
    "ChatMessage",
    "ChatRole",
    "ChatSession",
    "ConditionType",
    "CreditBand",
    "EscalationTier",
    "FinancialAssessment",
    "FinancialChecklistItem",
    "InteractionType",
    "KpiSearchResult",
    "LossChasingAssessment",
    "MinBetAudit",
    "MinBetCandidate",
    "MinBetChangeSource",
    "MinBetRecommendation",
    "MinBetRecommendationDrivers",
    "MinBetRecommendationStatus",
    "NextActionRecommendation",
    "OccupancyTrend",
    "OfferApprovalAudit",
    "OfferApprovalDecision",
    "OfferApprovalReview",
    "OfferCatalog",
    "OfferCreatedBy",
    "OfferRecommendation",
    "OfferStatus",
    "OfferType",
    "PRAgentProfile",
    "PRAssignment",
    "ParsedCondition",
    "PatronActivityEvent",
    "PatronAlert",
    "PatronAnalysisReport",
    "PatronInteractionDetail",
    "PatronInteractionRecord",
    "PatronProfile",
    "PatronRegion",
    "PatronRiskCase",
    "PatronTableSession",
    "PatronTier",
    "PrKpiResult",
    "PrMetrics",
    "RecommendationStatus",
    "ReportStatus",
    "RiskCaseStatus",
    "RiskCaseTimelineEvent",
    "RiskLevel",
    "SourceOfFundsRisk",
    "TableGameType",
    "TableRoundSnapshot",
    "TableStateHistory",
    "TableStateSnapshot",
    "TableStatus",
]
